apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: turbine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: turbine
    app.kubernetes.io/part-of: turbine
  name: turbine
  namespace: user1-tenant
spec:
  path: /
  port:
    targetPort: "8081"
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: turbine
    weight: null
status: {}
